apiVersion: v1
kind: Service
metadata:
  name: examencloud1manuel
  labels:
    name: examencloud1
    app: testing-kube-app
spec:
  type: NodePort
  selector:
    app: testing-kube-app
  ports:
    - protocol: TCP
      port: 5500
      nodePort: 30227



    